name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.111.3'
        extended: true

    - name: Debug - List repository contents
      run: |
        ls -la
        echo "Content directory:"
        ls -la content || echo "No content directory found"
        echo "Config directory:"
        ls -la config || echo "No config directory found"
        
    - name: Build
      run: |
        hugo --config config.toml --minify --verbose
        
    - name: Debug - Check generated files
      run: |
        echo "Public directory contents:"
        ls -la public || echo "No public directory found"
        echo "Public directory structure:"
        find public -type f | sort || echo "No files in public directory"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages